---
image: registry.gitlab.com/aplus-framework/images/php

include:
  - template: Security/SAST.gitlab-ci.yml

test:php:
  stage: test
  cache:
    paths:
      - vendor/
  before_script:
    - composer install
  script:
    - composer normalize --dry-run --indent-size=4 --indent-style=space
    - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
